language: ruby

cache: bundler

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database saver_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

rvm:
  - 2.0.0
