language: ruby

rvm:
  - 2.0.0

cache: bundler

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database saver_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

script:
  - ./bin/rake db:test:prepare
  - ./bin/rspec
